-- Generated from generator/demo_specs/aws-vietnam-aquaculture-feed.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-vietnam-aquaculture-feed
-- This is the schema that is actually deployed for VIETNAM_AQUACULTURE_FEED.

-- Alerts fire on the top tail of FCR (Avg)
-- (higher is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.91) WITHIN GROUP (ORDER BY KPI_FCR_AVG) AS T
  FROM RAW.FEED_EVENTS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_FCR_AVG >= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_FCR_AVG), 2) AS AVG_FCR,
  ROUND(AVG(f.KPI_PROTEIN_CONTENT), 2) AS AVG_PROTEIN_CONTENT,
  ROUND(AVG(f.KPI_OMEGA_3_LEVEL), 2) AS AVG_OMEGA_3_LEVEL,
  ROUND(AVG(f.KPI_PELLET_DURABILITY), 2) AS AVG_PELLET_DURABILITY
FROM RAW.FEED_EVENTS f
JOIN RAW.PONDS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_FCR_AVG), 2) AS AVG_FCR,
  ROUND(AVG(f.KPI_PROTEIN_CONTENT), 2) AS AVG_PROTEIN_CONTENT,
  ROUND(AVG(f.KPI_OMEGA_3_LEVEL), 2) AS AVG_OMEGA_3_LEVEL,
  ROUND(AVG(f.KPI_PELLET_DURABILITY), 2) AS AVG_PELLET_DURABILITY
FROM RAW.FEED_EVENTS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_FCR_AVG) AS KPI_FCR_AVG, AVG(KPI_PROTEIN_CONTENT) AS KPI_PROTEIN_CONTENT, AVG(KPI_OMEGA_3_LEVEL) AS KPI_OMEGA_3_LEVEL, AVG(KPI_PELLET_DURABILITY) AS KPI_PELLET_DURABILITY FROM RAW.FEED_EVENTS),
     en AS (SELECT SUM(KPI_FEED_PRODUCED_MTD) AS KPI_FEED_PRODUCED_MTD, SUM(KPI_RAW_MATERIAL_COST) AS KPI_RAW_MATERIAL_COST, SUM(KPI_FARMS_SUPPLIED) AS KPI_FARMS_SUPPLIED FROM RAW.PONDS)
  SELECT 1 AS SORT_ORDER, 'Feed Produced (MTD)' AS TITLE, KPI_FEED_PRODUCED_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_FEED_PRODUCED_MTD) / 1000)) AS DECIMAL(38,0))) || 'K' || ' ' || 'MT' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'FCR (Avg)' AS TITLE, KPI_FCR_AVG AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FCR_AVG), 2) AS DECIMAL(38,2))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Raw Material Cost' AS TITLE, KPI_RAW_MATERIAL_COST AS VALUE_NUM, '₫' || TO_VARCHAR(CAST(ROUND(((KPI_RAW_MATERIAL_COST) / 1000000000)) AS DECIMAL(38,0))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Farms Supplied' AS TITLE, KPI_FARMS_SUPPLIED AS VALUE_NUM, LTRIM(TO_VARCHAR(CAST(ROUND((KPI_FARMS_SUPPLIED)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Protein Content' AS TITLE, KPI_PROTEIN_CONTENT AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PROTEIN_CONTENT)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Omega-3 Level' AS TITLE, KPI_OMEGA_3_LEVEL AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_OMEGA_3_LEVEL), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Pellet Durability' AS TITLE, KPI_PELLET_DURABILITY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PELLET_DURABILITY)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
